sudo docker build -t tomato_ai_db .
[+] Building 38.4s (5/8)                                                                docker:default
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 427B                                                              0.0s
 => [internal] load metadata for docker.io/library/python:3.11                                    6.9s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 2B                                                                   0.0s
 => CANCELED [1/4] FROM docker.io/library/python:3.11@sha256:b762110707b9b089e8f6a204b8ed77e656  31.3s
 => => resolve docker.io/library/python:3.11@sha256:b762110707b9b089e8f6a204b8ed77e656d2338b630a  0.0s
 => => sha256:69313d3c151e29f9d4e11d62761399d0d7a84ecb75b15de4cc2f49e233c469da 6.18kB / 6.18kB    0.0s
 => => sha256:23b7d26ef1d294256da0d70ce374277b9aab5ca683015073316005cb63d33849 2.10MB / 48.49MB  31.3s
 => => sha256:07d1b5af933d2dfc3d0dd509d6e20534825e4a537f7b006a6cb5b8e5a1f20905 2.10MB / 24.01MB  31.3s
 => => sha256:1eb98adba0eb44a2e4facf9ca3626a4a66feedd0dd56d159cca90a35205744e7 1.05MB / 64.40MB  31.3s
 => => sha256:b762110707b9b089e8f6a204b8ed77e656d2338b630aabcedcede312fe077803 9.08kB / 9.08kB    0.0s
 => => sha256:84eda2e382bc609a73c2026d1185d37c39ad7f99876774d3b6ab1c3982035675 2.33kB / 2.33kB    0.0s
 => CANCELED [internal] load build context                                                       31.3s
 => => transferring context: 2.55GB                                                              31.3s
ERROR: failed to solve: Canceled: context canceled
muvunyi@muvunyi:~/Documents/code/tomato_ai$ 